afi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('afi_web.urls')),
]

afi_web/urls.py
from django.urls import path
from . import views

app_name = "afi_web"
urlpatterns = [
    path("login", views.login, name="login"),
    path("", views.index, name="index"),
    path("overview", views.overview, name="overview"),
    path("our-value", views.ourValue, name="ourValue"),
    path("our-culture", views.ourCulture, name="ourCulture"),
    path("our-team", views.ourTeam, name="ourTeam"),
    path("our-message", views.ourMessage, name="ourMessage"),
    path("development", views.development, name="development"),
    path("investment", views.investment, name="investment"),
    path("consulting", views.consulting, name="consulting"),
    path("epc", views.epc, name="epc"),
    path("onm", views.onm, name="onm"),
    path("data", views.data, name="data"),
    path("kawamura", views.kawamura, name="kawamura"),
    path("nagao", views.nagao, name="nagao"),
    path("wika", views.wika, name="wika"),
    path("maria", views.maria, name="maria"),
    path("asep", views.asep, name="asep"),
    path("rosi", views.rosi, name="rosi"),
    path("andrie", views.andrie, name="andrie"),
    path("kemas", views.kemas, name="kemas"),
    path("ancha", views.ancha, name="ancha"),
    path("recruitment", views.recruitment, name="recruitment"),
    path("where-we-are", views.whereWeAre, name="whereWeAre"),
]

afi_web/models.py
from django.db import models

# Create your models here.

afi_web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
# Create your views here.

class Login(forms.Form):
    name = forms.CharField(label="username")
    pswd = forms.CharField(label="password")

def login(request):
	return render(request, "afi_web/login.html", {
		"form": Login()	
	})

def index(request):
	return render(request, "afi_web/index.html")

def overview(request):
	return render(request, "afi_web/overview.html")

def ourValue(request):
	return render(request, "afi_web/our_value.html")

def ourCulture(request):
	return render(request, "afi_web/our_culture.html")

def ourTeam(request):
	return render(request, "afi_web/our_team.html")

def ourMessage(request):
	return render(request, "afi_web/our_message.html")

def development(request):
	return render(request, "afi_web/development.html")

def investment(request):
	return render(request, "afi_web/investment.html")

def consulting(request):
	return render(request, "afi_web/consulting.html")

def epc(request):
	return render(request, "afi_web/epc.html")

def onm(request):
	return render(request, "afi_web/onm.html")

def data(request):
	return render(request, "afi_web/data.html")

def kawamura(request):
	return render(request, "afi_web/kawamura.html")

def nagao(request):
	return render(request, "afi_web/nagao.html")

def wika(request):
	return render(request, "afi_web/wika.html")

def maria(request):
	return render(request, "afi_web/maria.html")

def asep(request):
	return render(request, "afi_web/asep.html")

def rosi(request):
	return render(request, "afi_web/rosi.html")

def andrie(request):
	return render(request, "afi_web/andrie.html")

def kemas(request):
	return render(request, "afi_web/kemas.html")

def ancha(request):
	return render(request, "afi_web/ancha.html")

def recruitment(request):
	return render(request, "afi_web/recruitment.html")

def whereWeAre(request):
	return render(request, "afi_web/where_we_are.html")

afi_web/templates/afi_web/ancha.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Team</div>
		</div>
	</section>
	<main id="page36" class="member">
		<section class="hero">
			<div class="box">
				<div class="name">Ancha</div>
				<div class="position">Executive Advisor</div>
			</div>
			<div class="quote">"Yang penting senang."</div>
		</section>
		<section class="biodata">
			<div class="container">
				<div class="box">
					<div class="title">Joined AFI</div>
					<div class="description">
						<p>December</p>
						<p>2020</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hometown</div>
					<div class="description">
						<p>Sengkang</p>
						<p>Indonesia</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Experience</div>
					<div class="description">
						<p>Human Resource</p>
						<p>Consultant</p>
						<p>Government Relation</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hobbies</div>
					<div class="description">
						<p>Reading books</p>
						<p>Futsal</p>
						<p>Badminton</p>
					</div>
				</div>
			</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/andrie.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Team</div>
		</div>
	</section>
	<main id="page34" class="member">
		<section class="hero">
			<div class="box">
				<div class="name">Andrie</div>
				<div class="position">Manager</div>
				<div class="division">Business Development Dept</div>
			</div>
			<div class="quote">"The harder you try,
				the better it will feel when you succeed."</div>
		</section>
		<section class="biodata">
			<div class="container">
				<div class="box">
					<div class="title">Joined AFI</div>
					<div class="description">
						<p>June</p>
						<p>2020</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hometown</div>
					<div class="description">
						<p>Majalengka</p>
						<p>Indonesia</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Experience</div>
					<div class="description">
						<p>CAD/CAM Engineer</p>
						<p>Community Development</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hobbies</div>
					<div class="description">
						<p>Futsal</p>
					</div>
				</div>
			</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/consulting.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Consulting</div>
		</div>
	</section>
	<main id="page22" class="blog1">
		<section class="hero">
		<h1 class="title">Consulting</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article>
			<h2>Invest in Solar Panels</h2>
			<h3>
				Solar Business is one of the most important aspect in processing
				renewable energy.
			</h3>
			<p>
				Renewable energy accounts for 18% of Japan's electricity supply.
				The national goal of "raising to 22-24% in 2030" is largely
				lacking. Solar power has grown rapidly since the FIT came into
				force in 2012, but still only 13%.
			</p>
			<p>
				How can we create the necessary green electricity in Japan, which
				has a small land area? How can we cope with the lack of free space
				in the power grid?
			</p>
			</article>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/data.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Data</div>
		</div>
	</section>
	<main id="page25" class="blog1">
		<section class="hero">
		<h1 class="title">Data</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article>
			<h2>Invest in Solar Panels</h2>
			<h3>
				Solar Business is one of the most important aspect in processing
				renewable energy.
			</h3>
			<p>
				Renewable energy accounts for 18% of Japan's electricity supply.
				The national goal of "raising to 22-24% in 2030" is largely
				lacking. Solar power has grown rapidly since the FIT came into
				force in 2012, but still only 13%.
			</p>
			<p>
				How can we create the necessary green electricity in Japan, which
				has a small land area? How can we cope with the lack of free space
				in the power grid?
			</p>
			</article>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/development.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Development</div>
		</div>
	</section>
	<main id="page20" class="blog1">
		<section class="hero">
		<h1 class="title">Development</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article>
			<h2>Solar Business</h2>
			<h3>
				Solar Business is one of the most important aspect in processing
				renewable energy.
			</h3>
			<p>
				Renewable energy accounts for 18% of Japan's electricity supply.
				The national goal of "raising to 22-24% in 2030" is largely
				lacking. Solar power has grown rapidly since the FIT came into
				force in 2012, but still only 13%.
			</p>
			<p>
				How can we create the necessary green electricity in Japan, which
				has a small land area? How can we cope with the lack of free space
				in the power grid?
			</p>
			</article>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/epc.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ EPC</div>
		</div>
	</section>
	<main id="page23" class="blog1">
		<section class="hero">
		<h1 class="title">EPC</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article class="bold">
			<p>
				What is EPC that afterFIT thinks about? Designed for the land, It
				is a construction that maximizes the income from selling
				electricity.
			</p>
			<p>afterFIT EPC has 3 commitments.</p>
			</article>
			<img src="static\afi_web\pic\crop\epc1.png" alt="gambar" />
			<article>
			<p>3D design to control shadows</p>
			<p>
				It is common sense that "it is not good for solar panels to be
				shaded."
			</p>
			<p>
				However, few people know how much shadows affect power generation.
			</p>
			<p>
				In fact, the amount of power generated may decrease by 60 to 70%
				with only a 3 cm shadow on the edge of the panel. *
			</p>
			<p>There are various conditions.</p>
			<p>
				At afterFIT, we are particular about the design that produces the
				maximum amount of power generation by thoroughly eliminating the
				shadow that is the enemy.
			</p>
			</article>
			<article>
			<p>For example,</p>
			<p>
				The power plants in the video below do not dare to even out the
				arrays so that the panels do not cast shadows in any season or
				time of day.
			</p>
			</article>
			<img src="static\afi_web\pic\crop\epc2.png" alt="gambar" />
			<article>
			<p><strong>Drone</strong></p>
			<p>
				AfterFIT has introduced surveying using drones. Not only accurate
				terrain but also shadows caused by surrounding trees and obstacles
				are assumed and analyzed, enabling design that maximizes the
				potential of the land.
			</p>
			</article>
			<img src="static\afi_web\pic\crop\epc3.png" alt="gambar" />
			<article>
			<p>
				Wiring design that increases power generation by up to 20%
				Increases power generation by up to 20% Wiring design Did you know
				that the amount of electricity generated can differ by up to 20%
				depending on the design and construction of the wiring?
			</p>
			<p>
				Based on the wiring diagram designed by the elite team through
				careful calculation, experienced technicians perform the
				construction without waste and realize the wiring with the minimum
				power generation loss.
			</p>
			</article>
			<div class="two-images">
			<img src="static\afi_web\pic\crop\epc4.png" alt="gambar" />
			<img src="static\afi_web\pic\crop\epc5.png" alt="gambar" />
			</div>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/investment.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Investment</div>
		</div>
	</section>
	<main id="page21" class="blog1">
		<section class="hero">
		<h1 class="title">Investment</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article>
			<h2>Invest in Solar Panels</h2>
			<h3>
				Solar Business is one of the most important aspect in processing
				renewable energy.
			</h3>
			<p>
				Renewable energy accounts for 18% of Japan's electricity supply.
				The national goal of "raising to 22-24% in 2030" is largely
				lacking. Solar power has grown rapidly since the FIT came into
				force in 2012, but still only 13%.
			</p>
			<p>
				How can we create the necessary green electricity in Japan, which
				has a small land area? How can we cope with the lack of free space
				in the power grid?
			</p>
			</article>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/kawamura.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Team</div>
		</div>
	</section>
	<main id="page28" class="member">
		<section class="hero">
			<div class="box">
				<div class="name">Kawamura</div>
				<div class="position">Director</div>
			</div>
			<div class="quote">"Whatever will be, will be."</div>
		</section>
		<section class="biodata">
			<div class="container">
				<div class="box">
					<div class="title">Joined AFI</div>
					<div class="description">
						<p>Founding Member</p>
						<p>November</p>
						<p>2019</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hometown</div>
					<div class="description">
						<p>Arashiyama</p>
						<p>Kyoto</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Experience</div>
					<div class="description">
						<p>Renewable Energy</p>
						<p>Finance</p>
						<p>Risk Assesment</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hobbies</div>
					<div class="description">
						<p>Sonowboarding</p>
					</div>
				</div>
			</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/kemas.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Team</div>
		</div>
	</section>
	<main id="page35" class="member">
		<section class="hero">
			<div class="box">
				<div class="name">Kemas</div>
				<div class="position">Manager</div>
				<div class="division">Project Development Dept</div>
			</div>
			<div class="quote">"Any fool knows that to work hard
				on things you want to accomplish is
				the only way to be happy."</div>
		</section>
		<section class="biodata">
			<div class="container">
				<div class="box">
					<div class="title">Joined AFI</div>
					<div class="description">
						<p>August</p>
						<p>2020</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hometown</div>
					<div class="description">
						<p>Sapporo</p>
						<p>Japan</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Experience</div>
					<div class="description">
						<p>Oil and Gas EPCr</p>
						<p>Project Management</p>
					</div>
				</div>
				<div class="box">
					<div class="title">Hobbies</div>
					<div class="description">
						<p>Mountaineering</p>
					</div>
				</div>
			</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/login.html
<!DOCTYPE html>
<html>
	<head>
		<title>afterFIT Indonesia</title>
	</head>
	<body>
		<form action="{% url 'afi_web:index' %}" method="post">
			{% csrf_token %}
			{{ form }}
			<input type="submit">
		</form>
	</body>
</html>

afi_web/templates/afi_web/onm.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>What We Do</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ O&M</div>
		</div>
	</section>
	<main id="page24" class="blog1">
		<section class="hero">
		<h1 class="title">O&M</h1>
		</section>
		<section class="seca">
		<div class="container">
			<article class="bold">
			<p>What is O & M that afterFIT thinks about?</p>
			<p>It is "preventive maintenance".</p>
			</article>
			<article>
			<p>
				When you find a problem at a power plant, afterFIT doesn't just
				solve it.
			</p>
			<p>
				Identify the cause of the problem and take fundamental measures to
				prevent the same from happening By doing so, we will support the
				stable operation of the power plant for 20 years.
			</p>
			</article>
			<img src="static\afi_web\pic\crop\onm1.png" alt="onm" />
			<article>
			<p>Operation</p>
			<p>
				Always monitor for any abnormalities and should be. Monitor if
				there is any discrepancy with the amount of power generated.
				"Departure that should be
			</p>
			<p>
				"Electric charge" is calculated from the amount of solar radiation
				in the area.
			</p>
			<p>
				The potential that the power plant originally has That's Yar. Stay
				on alert monitoring
			</p>
			<p>
				Not reaching the desired amount of power generation I think that
				something is wrong
			</p>
			<p>Eh, always by a professional team</p>
			<p>Nittering is done.</p>
			</article>
			<img src="static\afi_web\pic\crop\onm2.png" alt="onm" />
			<article>
			<p>Maintenance</p>
			<p>
				Maintenance and inspection to maintain stable power generation for
				20 years to hold. Just go to the power plant and look at it
			</p>
			<p>Maintenance is outdated. Visually abnormal</p>
			<p>Of course, it develops abnormally</p>
			<p>See signs of doing and deal with them in advance</p>
			<p>Top quality mail to prevent troubles</p>
			<p>We provide maintenance.</p>
			</article>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/our_culture.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>Who We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Culture</div>
		</div>
	</section>
	<main id="page17">
		<section class="hero">
		  <h1 class="title">Our Culture</h1>
		</section>
		<section class="seca">
		  	<div class="container">
				<article>
				<h1>Freedom and Responsibility</h1>
				<p>To make Indonesia the wealthiest country in the world.</p>
				</article>
				<article>
				<h1>Flat Culture</h1>
				<p>
					where everyone has the freedom to challenge themselves and bring
					the organization to newer heights.
				</p>
				</article>
				<article>
				<h1>Initiative</h1>
				<p>
					Where everyone is given the chance to explore new possibilities.
				</p>
				</article>
				<article>
				<h1>Dynamic Solution</h1>
				<p>
					Quick-paced in decision making as well as readiness to take action
					on any given opportunity.
				</p>
				</article>
		 	</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/our_team.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>Who We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Team</div>
		</div>
	</section>
	<main id="page18">
		<section class="hero">
		<h1 class="title">Our Team</h1>
		</section>
		<section class="seca">
		<div class="container">
			<div class="title">We Value our Members</div>
			<div class="description">
			Our team consists of people from various backgrounds with a
			challenger mentality. Each individual are important in our
			organization to actualize our vision and values.
			</div>
		</div>
		</section>
		<section class="secb">
		<div class="container">
			<div class="title">Meet Out Team</div>
			<div class="people-container">
			<div class="people people-1" onclick="kawamura()">
				<div class="img"></div>
				<div class="description-box" onclick="">
				<div class="name">Kawamura</div>
				<div class="position">Director</div>
				</div>
			</div>
			<div class="people people-2" onclick="nagao()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Nagao</div>
				<div class="position">Sales Manager</div>
				<div class="position">General Manager</div>
				<div class="departement">Business Development Div</div>
				</div>
			</div>
			<div class="people people-3" onclick="maria()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Maria</div>
				<div class="position">Finance Manager</div>
				<div class="position">General Manager</div>
				<div class="departement">Administration Div</div>
				</div>
			</div>
			<div class="people people-4" onclick="asep()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Asep</div>
				<div class="position">Manager</div>
				<div class="departement">Business Development Dept</div>
				</div>
			</div>
			<div class="people people-5" onclick="andrie()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Andrie</div>
				<div class="position">Manager</div>
				<div class="departement">Business Development Dept</div>
				</div>
			</div>
			<div class="people people-6" onclick="kemas()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Kemas</div>
				<div class="position">Manager</div>
				<div class="departement">Business Promotion Dept</div>
				</div>
			</div>
			<div class="people people-7" onclick="wika()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Wika</div>
				<div class="position">Manager</div>
				<div class="departement">Legal Dept</div>
				</div>
			</div>
			<div class="people people-8" onclick="rosi()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Rosi</div>
				<div class="position">Manager</div>
				<div class="departement">Human Resource Dept</div>
				</div>
			</div>
			<div class="people people-9" onclick="ancha()">
				<div class="img"></div>
				<div class="description-box">
				<div class="name">Ancha</div>
				<div class="departement">Executive Advisor</div>
				</div>
			</div>
			</div>
		</div>
		</section>
	</main>
{% endblock %}

afi_web/templates/afi_web/our_value.html
{% extends "afi_web/layout.html" %}
{% block title %}
	AfterFit Indonesia
{% endblock %}
{% block body %}
	<section class="breadcrumb">
		<div class="container">
		<div class="black" role="button">
			<div>Who We Are</div>
			<svg
			class="down"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
			>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M19 9l-7 7-7-7"
			/>
			</svg>
		</div>
		<div class="gray">/ Our Value</div>
		</div>
	</section>
	<main id="page16">
		<section class="hero">
			<h1 class="title">Our Value</h1>
		</section>
		<section class="seca">
			<div class="container">
				<article>
				<h1>Vision</h1>
				<p>To make Indonesia the wealthiest country in the world.</p>
				</article>
				<article>
				<h1>Mission</h1>
				<p>
					We are solving all of the problems in Indonesia using PV Green
					Technology, as well as providing a sustainable clean energy for
					all.
				</p>
				</article>
				<article>
				<h1>Value</h1>
				<div class="sub-article">
					<h2>Responsibility</h2>
					<p>
					We're taking our challenges with full of responsibility in order
					to give definitive contribution to this country.
					</p>
				</div>
				<div class="sub-article">
					<h2>Curiosity</h2>
					<p>
					We are passionately driven by our curiosity to solve all the
					problems in our surroundings as well as constantly finding
					solutions to potential problems.
					</p>
				</div>
				<div class="sub-article">
					<h2>Inclusion</h2>
					<p>
					We achieve our goals by working efficiently by synergizing our
					strengths from various diversities and cultures.
					</p>
				</div>
				</article>
			</div>
		</section>
	</main>
{% endblock %}